name: My Github Actions Workflow

on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-latest

    steps: 
    - name: Hello
      run: echo "Hello World"
    - name: Display repo name
      run: echo "Repo name is ${{ github.repository }}"